### ISSUE TITLE
Migration doubt

### ISSUE THREAD

**Issue by miquelalvarado** [braze-inc/braze-segment-swift#10]
Hi!

We are currently migrating Braze to the Swift version, as well as the Segment plugin for Braze and I have a doubt: In the objC version of the library we had `saveRemoteNotification` as well as `saveLaunchOptions` to store any received userInfo while Braze was still uninitialized. I'm not seeing anything similar for the new destination plugin. How are we intended to proceed with this during the migration? what's your recommendation?

Thanks!

**Comment by jerielng** [comment]
Hey @miquelalvarado, we don't support this in the new Swift Segment plugin, but these functions from the older version should be achievable from your end. If you want to replicate this functionality, you can refer to the publicly available code [here](https://github.com/Appboy/appboy-segment-ios/blob/dc659b70f2b432f8c70fda869b27eac2acb688fe/Pod/Classes/SEGAppboyIntegrationFactory.m#L45-L60) and maintain a reference to the stored payload in your application.

Should that be sufficient for your needs? If not, feel free to let us know by filing some [product feedback](https://dashboard.braze.com/resources/roadmap) and we can look into prioritizing it as a feature. Thanks!

**Comment by miquelalvarado** [comment]
Yes, we can do that of course, just wanted to know if the new Braze library handled that by its own or which is the recommended way to handle this kind of payload when the Braze sdk is not ready yet. 
So one last question, which methods should I call on the new library, to pass these stored `launchOptions` and/or `userInfo`?

**Comment by jerielng** [comment]
You should be able to call [`handleBackgroundNotification`](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/notifications-swift.class/handlebackgroundnotification(userinfo:fetchcompletionhandler:))  on your Braze instance to send up the payload.

```swift
braze.notifications.handleBackgroundNotification(userInfo: {your-dictionary}, fetchCompletionHandler: {your-handler})
```

You can access the Braze instance [here](https://github.com/braze-inc/braze-segment-swift/blob/main/Example/BasicExample/BasicExampleApp.swift#L45-L48) in your app when you initialize the `BrazeDestination`.
