### ISSUE TITLE
can I use Braze's "Automatic push integration" with "braze-segment-swift"?

### ISSUE THREAD

**Issue by skydivedan** [braze-inc/braze-segment-swift#12]
OK, first I believe that the answer is already "no", but I'm looking for guidance on this...

the "braze-segment-swift" plugin instantiates its own "Braze" instance, after it receives configuration information from Segment.

But when I look at the Braze documentation, for setting up push notifications, it talks about doing it "automatically"
https://www.braze.com/docs/developer_guide/platform_integration_guides/swift/push_notifications/integration/#automatic-push-integration
But then there's this caveat:
>The SDK must be initialized on the main thread to enable push notification automation. SDK initialization must happen before the application has finished launching or in your AppDelegate [application(_:didFinishLaunchingWithOptions:)](https://developer.apple.com/documentation/uikit/uiapplicationdelegate/1622921-application)  implementation

So, since Segment makes a web-service call to get all the configuration information, Braze get initialized by "braze-segment-swift" until after `didFinishLaunchingWithOptions` is called, right? So, does this mean that I need to use "Manual Push Integration"?

So, assuming that we need to to "Manual Push Integration",  I was also wondering if there's guidance on handling a push-notification that **launches** the app from a Braze campaign. If we get it on launch, then "braze-segment-swift" will not have initialized `Braze` yet, so we'll need to pass this along at some point after `Braze` in instantiated, right?

I guess I'm asking for either guidance, or perhaps a more comprehensive sample app, that demonstates how one sets up Braze push notifications, while also using "braze-segment-swift"

**Comment by hokstuff** [comment]
Hi @skydivedan,

Yes you are able to leverage Braze's Push Automation feature while using `braze-segment-swift`. You can reference [our sample app's implementation here](https://github.com/braze-inc/braze-segment-swift/blob/b19596c23b1f2d66389fab0ec1bcfaf8c8dff889/Example/BasicExample/BasicExampleApp.swift#L35-L37), which shows how you can inject different Push Automation properties when initializing Braze. [Here are the different properties](https://braze-inc.github.io/braze-swift-sdk/documentation/brazekit/braze/configuration-swift.class/push-swift.class/automation-swift.class) that can be used for this feature.

Let us know if you run into further issues on this! If you require more detailed support, you can also email us at support@braze.com.

Thanks!

**Comment by skydivedan** [comment]
Hi @hokstuff,

I've created a ticket with support@braze.com

But I'd like to explain my original question a bit.

When the app launches, it connects to Segment, and Segment sends back various configuration information about various destinations, including Braze. Once we receive the configuration information from Braze, we are then able to create a Braze instance.

**However**, what if the app has quit (actually quit, not just backgrounded) and the app gets launched by a Push Notification that gets sent to it by a Braze campaign?
In this case, the app will receive a push-notification (through `application(_ application: UIApplication,
                     didReceiveRemoteNotification userInfo: [AnyHashable: Any],
                     fetchCompletionHandler...`) long before we receive the configurations sent to us from Segment, won't it? In that case, we won't be able to track that we received this notification, because it already got processed before Braze was installed, right?

**Comment by hokstuff** [comment]
Hi @skydivedan,

Thanks for clarifying your question. When the host app is terminated and you click on a push notification, it will call 1) `didFinishLaunchingWithOptions` and then 2) `didReceiveNotificationResponse`. It is during 2) that we are able to attribute a push click to be a "Direct Open" for metrics ([see our sample app](https://github.com/braze-inc/braze-swift-sdk/blob/f893978502a08b02124d2d15c6117eb1a06b7f6f/Examples/Swift/Sources/PushNotifications-Manual/AppDelegate.swift#L76-L79) that manually implements push notifications for reference).

> In this case, the app will receive a push-notification long before we receive the configurations sent to us from Segment, won't it? In that case, we won't be able to track that we received this notification, because it already got processed before Braze was installed, right?

I have not been able to confirm this, but this sounds like a valid concern, given we don't have full visibility around Segment's technical implementation with their Destinations. If you are seeing incorrect metrics in your app around push clicks from the terminated state, then it might be due to what you described, and you can instead use the Manual push integration.

From Braze's side, we are actively working on allowing delayed initialization of the Braze instance while also being compatible with push notifications. Specifically, we're working on a solution that allows a host app to receive push notifications with valid metrics, even if these notifications come in prior to Braze being initialized. In this world, I'd expect that these concerns would be addressed as well.

Thanks!

**Comment by lowip** [comment]
Hi @skydivedan,

Thank you for your patience, we have released version [`3.0.0`](https://github.com/braze-inc/braze-segment-swift/releases/tag/3.0.0) which allows you to use versions `1.5.0+` of https://github.com/segmentio/analytics-swift and keep the push notification support working.

Please be aware that this is a major release which requires a small change in the integration. All details can be found in the [changelog entry](https://github.com/braze-inc/braze-segment-swift/blob/main/CHANGELOG.md#300).

On a technical note, the new required change will ensure that notification related events (e.g. device token, push notification opened, etc.) are enqueued and processed by Braze once it is initialized by Segment.

**Comment by skydivedan** [comment]
@lowip - This is great, thanks for getting this in there, looking forward to adopting this as soon as I can. Just one question though... why does the call look like this:
`Braze._prepareForDelayedInitialization`
Like, can this be called without the underscore? Just curious.

**Comment by lowip** [comment]
Hey @skydivedan,

`Braze._prepareForDelayedInitialization()` is not yet available "publicly" (it is a public symbol, though not fully documented, hence the `_` prefix). It has been thoroughly tested with our Segment's DestinationPlugin, but the API is not final for general usage in our Swift SDK while we reach alignment with our Android SDK.

For the time being, we advise you to use the `BrazeDestination.prepareForDelayedInitialization()` alias which will remain stable for the foreseeable future.
