### ISSUE TITLE
Compatibility with 9.x.x 

### ISSUE THREAD

**Issue by gemmakbarlow** [braze-inc/braze-segment-swift#13]
I'm needing to upgrade our Braze integration to use https://github.com/braze-inc/braze-swift-sdk.git 9.0.0, but the latest version of `braze-segment-swift`, 2.3.0, doesn't support this.

Are you able to provide a rough timeline for a compatible version ? 

Thanks !

**Comment by lowip** [comment]
Hi @gemmakbarlow,

We have just released [2.4.0](https://github.com/braze-inc/braze-segment-swift/releases/tag/2.4.0) which allows you to upgrade to the Braze Swift SDK 9.0.0+.

Best,
