### ISSUE TITLE
Support for Braze Swift SDK 11+

### ISSUE THREAD

**Issue by dm-ben** [braze-inc/braze-segment-swift#14]
I'm needing to upgrade our Braze integration to use https://github.com/braze-inc/braze-swift-sdk.git 11.0.0, but the latest version of braze-segment-swift, 4.0.0, doesn't support this.

Are you able to provide a rough timeline for a compatible version ?

Thanks !

**Comment by hokstuff** [comment]
Thanks for raising this! We will move forward with bumping the bindings for our SDK in our private repo and then begin the process of validating + releasing into our public repo shortly after. We'll aim to get this out within the next week or so.

**Comment by lowip** [comment]
Hi @dm-ben,

We have released [5.0.0](https://github.com/braze-inc/braze-segment-swift/releases/tag/5.0.0) which allows using the Braze Swift SDK 11.1.1+.

Best,
