### ISSUE TITLE
Request to Update analytics-swift Dependency to Address Repeated "Application Installed" Events

### ISSUE THREAD

**Issue by sunil-prezzee** [braze-inc/braze-segment-swift#15]
Hi there, 

I noticed that `braze-segment-swift` currently relies on an older version of analytics-swift:

```
.package(
    url: "https://github.com/segmentio/analytics-swift",
    from: "1.1.2"
)
```

There’s been an important fix in [PR #359](https://github.com/segmentio/analytics-swift/pull/359) of analytics-swift, which resolves an issue where the "Application Installed" event was incorrectly triggered on every app launch. This update would be super helpful to ensure correct tracking behavior.

Would it be possible to update the dependency to include this fix? 

Thank you

**Comment by jerielng** [comment]
Hi @sunil-prezzee, thanks for bringing this to our attention! We'll take a look into it and assess the level of effort to bump this dependency. We'll keep you posted with any updates as we have them.

**Comment by jerielng** [comment]
Hey @sunil-prezzee, taking a closer look at this, could you confirm if this is blocking you? The `from:` syntax in a `Package.swift` indicates that you can use any version of that library or greater, up to the next major version.

In this case, we only require a minimum of `1.1.2` but do not lock the version to a maximum. The latest from Segment is currently `1.7.0`, so you should be able to manually update this on your end. Let us know if you are facing other issues.

**Comment by sunil-prezzee** [comment]
@jerielng - Thanks for your help and suggestion - as I have manually update too.
