### ISSUE TITLE
No way to set `triggerMinimumTimeInterval`

### ISSUE THREAD

**Issue by mickyzinho** [braze-inc/braze-segment-swift#5]
I don't see any possibility to set the `triggerMinimumTimeInterval` with Segment and this Braze integration. Both `Analytics` and `BrazeDestination` do not have this field in their api and the Braze instance within the destination is isolated. How is a Segment user supposed to access this? 
The `SEGAppboyIntegrationFactory` used to allow settings the `ABKMinimumTriggerTimeIntervalKey`, is the access removal on purpose, is this a bug, or is there an undocumented way to do this?

**Comment by jerielng** [comment]
Hey @mickyzinho, unfortunately, at the moment, this field isn't accessible within this integration of Braze and Segment. We have it on our roadmap to review and productionize this SDK, but in the meantime, we would recommend using the original [Appboy Segment](https://github.com/Appboy/appboy-segment-ios) integration while this is in progress.

Thanks for your patience, and let us know if you have any further questions!

**Comment by jerielng** [comment]
Hi @mickyzinho, we've just released version 2.0.0 of the Braze Segment plugin, which allows you to access the `triggerMinimumTimeInterval` property, along with other features.

Please let us know if you have any further questions. Thanks!
