### ISSUE TITLE
Update to latest versions of dependencies

### ISSUE THREAD

**Issue by eddernunez-earnin** [braze-inc/braze-segment-swift#6]
When should we expect maintenance to update to latest versions of:
- https://github.com/braze-inc/braze-swift-sdk
- https://github.com/segmentio/analytics-swift

**Comment by davidbielik** [comment]
Hi @eddernunez-earnin this is something our team is actively working on. While I don't have a timeline to share, it's something we're hoping to have completed in the next few months.

**Comment by jerielng** [comment]
Hi @eddernunez-earnin, we've just released version `2.0.0` of this plugin. Note that the repository has now moved to https://github.com/braze-inc/braze-segment-swift.

If you have any further questions, feel free to open a new thread. Thank you!
