### ISSUE TITLE
Crash on iOS 17 Beta latest release

### ISSUE THREAD

**Issue by maail** [braze-inc/braze-segment-swift#7]
There is a crash on iOS when I integrate Braze with Segment. This happens when I open the app.

My code is below:

```
let configuration = Configuration(writeKey: apiKey)
            .trackApplicationLifecycleEvents(true)
            .flushAt(3)
            .flushInterval(10)
var analytics: Analytics? = nil
analytics?.add(plugin: BrazeDestination())
```

Crash Details Below
```
Thread 3 Queue : com.braze.http (serial)
#0	0x0000000109612c00 in closure #1 in static HTTP.Client.Plugin.modify(urlComponents:) ()
#1	0x000000010955b090 in partial apply for closure #1 in static HTTP.Client.Plugin.modify(urlComponents:) ()
#2	0x000000010955de7c in closure #1 in static HTTP.Client.Plugin.modify(urlComponents:)partial apply ()
#3	0x00000001095583f8 in specialized URLRequest.init<τ_0_0>(api:plugins:) ()
#4	0x000000010955a9f0 in specialized implicit closure #1 in HTTP.Client.innerPerform(_:extraPlugins:) ()
#5	0x000000010955cb04 in specialized thunk for @escaping @callee_guaranteed (@in_guaranteed τ_0_0, @guaranteed [HTTP.Client<τ_0_0>.Plugin]) -> (@out URLRequest, @error @owned Error) ()

```

**Comment by jerielng** [comment]
Hi @maail, thanks for your report. We're currently in the process of fully productionizing the Braze Segment plugin.

We'll take a look into this crash as part of our productionization efforts and will keep you updated in this thread.

That being said, could you confirm 1) Is this happening only on the latest Xcode 15 beta and only on iOS 17 Simulators? 2) Does this happen with every app open, or is this a sporadic crash?

**Comment by maail** [comment]
1) Yes for both
2) Everytime you open the app

**Comment by jerielng** [comment]
Hey @maail, unfortunately, I'm not able to reproduce this on our side. Looking at the stack trace, it looks to be coming from the underlying Braze Swift SDK, and if I were to guess, it's most likely a crash when trying to create a URL object.

The Braze Segment integration should have the version of the Braze Swift SDK indicated in your Xcode project. Would you mind sharing which version this is? If you are willing, could you also share what value is being set as `brazeSettings.customEndpoint`? If you'd like, you can write into support@braze.com with this information and reference this GitHub issue for context.

**Comment by jerielng** [comment]
Hi @maail! Just wanted to follow up if you are still experiencing this and are able to provide the information descried above?

**Comment by hokstuff** [comment]
Also, we have actually added safeguards for malformed endpoints in our [7.7.0 Swift SDK release](https://github.com/braze-inc/braze-swift-sdk/releases/tag/7.7.0), which would prevent the app from crashing in this case. If you update to that version or newer, you should no longer see the crashes noted in the stack traces above.
