### ISSUE TITLE
Run before and enrichment plugins in the BrazeDestination plugin (to enable debounce middleware)

### ISSUE THREAD

**Issue by nickruddeni** [braze-inc/braze-segment-swift#8]
Using the old SDK, we were advised to utilise this bit of middleware to avoid sending duplicate identify calls to Braze, which costs money. https://github.com/segmentio/segment-braze-mobile-middleware

There is no provided alternative that works with Segments new plugin system in the segment-swift package. I tried to manually implement this however the problem is as follows:
- Segment runs adds its `DestinationMetadataPlugin` an enrichment step to its own `SegmentDestination` plugin
- We want to run our middleware *after* that step, but before the `BrazeDestination` sends its event.
- This should be easy as you can add `before` and `enrichment` plugins to a specific `DestinationPlugin`, however, the `BrazeDestination` plugin is not running any of the plugins added to it's timeline, as it provides a different implementation of `execute(event:)`. See `SegmentDestination` for how they run timeline plugins before there own event code.

Do you have any advice on the best approach to implementing the debounce plugin? I suggest removing the `execute(event:)` implementation in `BrazeDestination` and using the default provided by Segment that runs the timeline middleware. The code for adding setting the IDFA  on Braze can be moved to it's own plugin

**Comment by jerielng** [comment]
Hey @nickruddeni, thanks for the suggestion! We'll definitely want to scope this out and design a long-term solution for implementing debouncing as it may impact the way the Braze plugin is architected. We've filed an internal ticket to look into this and will keep you updated here on its progress.

**Comment by nickruddeni** [comment]
Ah ok great. I opened a PR to show how we're working around it for now on a fork. Feel free to close that if you have a longer-term solution in mind!

**Comment by hokstuff** [comment]
Hi @nickruddeni,

We have folded in the changes in your public PR into our private repo (as per our internal release process) and have released the changes in [version 2.3.0 of our Braze Segment Swift plugin](https://github.com/braze-inc/braze-segment-swift/releases/tag/2.3.0)! Let us know if you run into any issues.

Thank you for your contribution!
